apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.myLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.myLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.myLabel }}
    spec:
      containers:
        - name: {{ .Values.myLabel }}
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          ports:
            - containerPort: {{ .Values.service.targetPort }}