apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.myLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.myLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.myLabel }}
    spec:
      containers:
        - name: {{ .Values.myLabel }}
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          volumeMounts:
          - name: {{ .Values.volumeMounts.name}}
            mountPath: {{ .Values.volumeMounts.mountPath }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
      imagePullSecrets:
        - name: "web-app-key"
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistent.name }}