apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistent.name }}
spec:
  accessModes:
    - {{ .Values.persistent.accessMode }}
  storageClassName: {{ .Values.persistent.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistent.size }}