name: CI CD pipeline

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.64.0 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          DEFAULT_BUMP: patch
          WITH_V: true
          INITIAL_VERSION: 1.0.0
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag app:${{ steps.tag.outputs.new_tag }}
  
  push_to_registry:
    name: Push docker image to registry
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push to dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ steps.tag.outputs.new_tag }}


# jobs:
#   deployment:
#     runs-on: ubuntu-latest
#     steps: 
#     - uses: actions/checkout@v3

#     - name: Deploy
# test