name: CI CD pipeline

on:
  pull_request:
    types: [closed]

env: 
  region: "us-east-1"
  cluster_name: "terraform-eks-cluster"

jobs:
  build:
    name: build and push docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.64.0 
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }} 
          DEFAULT_BUMP: patch
          WITH_V: false
          INITIAL_VERSION: 1.0.0

      - name: Build the Docker image and tag
        run: |
          docker build . --file Dockerfile --tag app:${{ steps.tag.outputs.new_tag }}
          docker tag app:${{ steps.tag.outputs.new_tag }} ofekmalul/web_app:${{ steps.tag.outputs.new_tag }}

      - name: Log in to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # - name: Push to dockerhub
      #   run: docker push ofekmalul/web_app:${{ steps.tag.outputs.new_tag }}
      
      - name: get the tag version from values.yaml and update
        run: |
          TAG_VERSION=$(grep "tags" weather_app_chart/values.yaml | awk -F: '{print $2}')
          sed -i "s/tag: \"$TAG_VERSION\"/tag: \"${{ steps.tag.outputs.new_tag }}\"/g" weather_app_chart/values.yaml
      
      - name: update github repository
        run: |
            git config --local user.email "ofekmalulmail@gmail.com"
            git config --local user.name "github actions"
            git status
            git add .
            git commit -m 'github action update the helm values.yaml file'
            git push

  deploy:
     name: deploy helm chart to eks
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v4

       - name: configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: $region

        # This command aws eks update kubeconfig will retrive the .kube file from eks so it can connect to the eks
       - name: Authenticate with EKS
         run: aws eks update-kubeconfig --name $cluster_name --region $region

       - name: Deploy Helm chart
         run: helm upgrade --install app weather_app_chart/