name: CI CD pipeline

on:
  pull_request:
    types: [closed]
    

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.64.0 
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }} 
          DEFAULT_BUMP: patch
          WITH_V: false
          INITIAL_VERSION: 1.0.0
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag app:${{ steps.tag.outputs.new_tag }}
        run: docker tag app:${{ steps.tag.outputs.new_tag }} ofekmalul/web_app:${{ steps.tag.outputs.new_tag }}

      - name: Log in to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push to dockerhub
        # uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        # with:
        #   context: .
        #   file: ./Dockerfile
        #   push: true
        #   tags: ${{ steps.tag.outputs.new_tag }}
        #   labels: ofekmalul/web_app
        run: docker push ofekmalul/web_app:${{ steps.tag.outputs.new_tag }} 

# jobs:
#   deployment:
#     runs-on: ubuntu-latest
#     steps: 
#     - uses: actions/checkout@v3

#     - name: Deploy
# test1