name: CI pipeline

on:
  pull_request:
    types: [closed]

jobs:
  integrate:
    name: Create image tag and push to Dockerhub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.tag.outputs.new_tag }} # Define an output for the version

    steps:
      - uses: actions/checkout@v4
    
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.64.0 
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }} 
          DEFAULT_BUMP: patch
          WITH_V: false
          INITIAL_VERSION: 1.0.0

      - name: Build the Docker image and tag
        run: docker build . --file Dockerfile --tag ofekmalul/web_app:${{ steps.tag.outputs.new_tag }}

      - name: Log in to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
           
      - name: Push to dockerhub
        run: docker push ofekmalul/web_app:${{ steps.tag.outputs.new_tag }}

  update-helm-chart:
    permissions:
      contents: write
    name: Update helm chart
    runs-on: ubuntu-latest
    needs: integrate
    if: success()

    steps:
      - name: Checkout helm repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.USERNAME_GITHUB }}/helm_charts
          token:  ${{ secrets.TOKEN_GITHUB }} # Provide the fine grained token inorder to be able to update a different repo from within the job
      
      - name: get the tag version from values.yaml and update
        run: |
          cd CreatedByMe/weather_app_chart
          cat values.yaml
          TAG_VERSION=$(grep "tag" values.yaml | awk -F: '{print $2}')
          sed -i "s/tag:$TAG_VERSION/tag: \"${{ needs.integrate.outputs.version }}\"/g" values.yaml
          cat values.yaml

      - name: update github repository
        run: |
            git config --global user.email "ofekmalulmail@gmail.com"
            git config --global user.name "OfekMalul"
            echo "TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}" >> $GITHUB_ENV
            git add .
            git status
            git commit -m 'github action update the helm values.yaml file'
            git push