# teset
name: CD pipeline

on:
  pull_request:
    types: [closed]

env: 
  REGION: "us-east-1"
  CLUSTER_NAME: "terraform-eks-cluster"

jobs:
  Deploy:
    name: Create image tag and push to Dockerhub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # needs: Build & Test
    # if: success()
    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}